name: Auto Create PR in Another Repository

on:
  pull_request:
    types:
      - opened

jobs:
  create_pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: HamiltonLopes/action-repo-qa-clone
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create new branch and change remote for the original repo
        run: | 
          git checkout -b ${{ github.event.pull_request.head.ref }}
          git remote set-url origin https://github.com/HamiltonLopes/action-repo-qa.git
      
      - name: Add config global
        run: | 
          git config --global user.email "hamilton_dino02@hotmail.com"
          git config --global user.name "Hamilton Lopes"

      - name: Push new branch
        run: |
          git push -u origin ${{ github.event.pull_request.head.ref }} --force

      - name: Create PR in Another Repository
        run: |
          gh pr create --base "${{ github.event.pull_request.base.ref }}" --head "${{ github.event.pull_request.head.ref }}" --title "Auto-created PR from ${{ github.event.pull_request.head.ref }}" --body "This is the pull request body."
